ComputeGC/urls.py
from django.conf.urls import url

from . import views

# Url patterns for this app
    path('computegc/', ComputeGC.views.HomeView.as_view(), name='form'),

blog/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView
from . import views


urlpatterns = [
    path('', PostListView.as_view(), name ='blog-home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name ='post-detail'),
    path('post/new/', PostCreateView.as_view(), name ='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name ='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name ='post-delete'),
    path('about/', views.about, name ='blog-about'),

]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

import ComputeGC.views

#pathways for all web pages
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name="register"),
    path('', include('blog.urls')),
    path('login/', auth_views.LoginView.as_view(template_name = "users/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name = "users/logout.html"), name="logout"),
    path('profile/', user_views.profile, name="profile"),
    path('computegc/', ComputeGC.views.HomeView.as_view(), name='form'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ComputeGC/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AnonymousUser, User

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
# These are databases

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs = {'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to="profile_pics")

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self, *args, **kawrgs):
        super().save(*args, **kawrgs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width >300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

ComputeGC/forms.py
from django import forms
from .models import *


# Default form for this application

class HomeForm(forms.Form):	

	# input field for this form		
	post = forms.CharField()

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields =['image']

ComputeGC/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import AnonymousUser, User
from django.http import HttpResponse
from django.views.generic import TemplateView
from .forms import HomeForm

from .process import computeGC
from .models import *


# Default view for this app

class HomeView(TemplateView):

	# Define template for this view
	template_name = 'ComputeGC/form.html'

	# Handle HTTP GET requests through this view

	def get(self, request):

		# Define the form
		form = HomeForm()

		# Render the page with the form included
		args = {'form': form,}
		return render(request, self.template_name, args)

	# Handle HTTP POST requests through this view

	def post(self, request):

		# Define the form
		form = HomeForm(request.POST)

		# Validate input
		if form.is_valid():

			# Store cleaned input data
			posted = form.cleaned_data['post']

			# Process data
			result = computeGC(form.cleaned_data['post'])

			# Clear text field
			form = HomeForm()										

		# Render the page with form and result data
		args = {'form': form, 'posted': posted, 'result': result}
		return render(request, self.template_name, args)

blog/views.py
from django.shortcuts import render
from .models import Post
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

def home(request):
    context = {
        'posts': Post.objects.all()
    } 
    return render(request, 'blog/home.html', context)

class PostListView(ListView):
    model = Post
    template_name ='blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']

class PostDetailView(DetailView):
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url='/'
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

def about(request):
    return render(request,'blog/about.html', {'title': 'About'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f'Your account has been created!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})
@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance = request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance = request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated')
            return redirect('profile')

    else:
        u_form = UserUpdateForm(instance = request.user)
        p_form = ProfileUpdateForm(instance = request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html', context)

ComputeGC/templates/ComputeGC/form.html
{% extends "blog/base.html" %}

{% block content %}

<!--Jumbotron header for this page-->
  <div class="container">
    <h1>Compute GC Content</h1>
  </div>
</div>

<div class="container text-center"><br><br>

  <!--UI form for this page-->
  <form method="POST">
    <!--Input validation token for security-->
    {% csrf_token %}
    <div class="row">
      <div class="col-md-1"></div>
      <div class="col-md-2 text-right">
        <label for="id_post">Input:</label>
      </div>
      <div class="col-md-8 text-left">
        <!--Input-->
        <textarea rows="3" cols="56" name="post" required id="id_post" />{{posted}}</textarea>
      </div>
    </div><br>
    <!--Submit-->
    <button type="submit">Submit</button>
  </form><br>

  <!--Output-->
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-2 text-right">
      <strong>GC Content:</strong>
    </div>
    <div class="col-md-8 text-left">
      {{result}}
    </div>
  </div>

</div>

{% endblock %}

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}

    <h1>About Page</h1>
  
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">

    {% if title %}
        <title>Django Blog - {{ title }}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
              <a class="nav-item nav-link" href="{% url 'form' %}">ComputeGC</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'post-create'%}">New Post</a>
                <a class="nav-item nav-link" href="{% url 'profile'%}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout'%}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login'%}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register'%}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alter alter-{{message.tags}}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}

    {% for post in posts %}
    <article class="media content-section">
        <img class = "rounded-circle article-img" src ="{{ post.author.profile.image.url}}"></img>
        <div class="media-body">
          <div class="article-metadata">
            <a class="mr-2" href="#">{{ post.author }}</a>
            <small class="text-muted">{{ post.date_posted| date:"F d, Y" }}</small>
          </div>
          <h2><a class="article-title" href="{% url 'post-detail' post.id%}">{{ post.title }}</a></h2>
          <p class="article-content">{{ post.content }}</p>
        </div>
      </article>
    {% endfor %}
{% endblock content %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}

    <div class="content-section">
        <form method = "POST">
            {% csrf_token %}
            <fieldset class= "form-group">
                <legend class = "border-bottom mb-4"> Delete Post </legend>
                <h2> Are you sure you want to delete "{{object.title}}"</h2>
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-danger" type ="submit">Yes, delete</button>
                <a class = "btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancle</a>
            </div>
        </form>
    </div>
    


{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% block content %}

<article class="media content-section">
    <img class = "rounded-circle article-img" src ="{{ object.author.profile.image.url}}"></img>
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="#">{{ object.author }}</a>
            <small class="text-muted">{{ object.date_posted| date:"F d, Y" }}</small>
            {% if object.author == user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1"href="{% url 'post-update' object.id %}">Update</a>
                    <a class="btn btn-danger btn-sm mt-1 mb-1"href="{% url 'post-delete' object.id %}">Delete</a>
                </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ object.title }}</h2>
        <p class="article-content">{{ object.content }}</p>
    </div>
</article>
{% endblock content %} 

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method = "POST">
            {% csrf_token %}
            <fieldset class= "form-group">
                <legend class = "border-bottom mb-4"> Blog Post </legend> 
                {{ form|crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type ="submit">Post</button>
            </div>
        </form>
    </div>
    


{% endblock content %}

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method = "POST">
            {% csrf_token %}
            <fieldset class= "form-group">
                <legend class = "border-bottom mb-4"> Log In </legend> 
                {{ form|crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type ="submit">Log In</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class= "text-muted">
                Need an Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
    


{% endblock content %}

users/templates/users/logout.html
{% extends "blog/base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class= "text-muted">
            <a href="{% url 'login' %}">Log in again</a>
        </small>
    </div>
    
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src= "{{ user.profile.image.url }}">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary"> {{ user.email }} </p>
        </div>
        </div>
        <form method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class= "form-group">
                <legend class = "border-bottom mb-4"> Profile Info </legend> 
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type ="submit">Update</button>
            </div>
        </form>
    </div>


{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="content-section">
        <form method = "POST">
            {% csrf_token %}
            <fieldset class= "form-group">
                <legend class = "border-bottom mb-4"> Join Today </legend> 
                {{ form|crispy }}
            </fieldset>
            <div class = "form-group">
                <button class = "btn btn-outline-info" type ="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class= "text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
    


{% endblock content %}